source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BelerLibrary_Example', :exclusive => true do
  pod 'BelerLibrary', :path => '../'
end

target 'BelerLibrary_Tests', :exclusive => true do
  pod 'BelerLibrary', :path => '../'

  
end
